### ISSUE TITLE
Missing script for generating "collect_files_dt_master_tissue.txt"

### ISSUE THREAD

**Issue by pauline-ng** [csmail/outlier_prs#1]
Hi Craig,

I'm trying to replicate your workflow.  A lot of the scripts use a file called **collect_files_dt_master_tissue.txt**

Can you upload the script that generates that file?

Thanks,
Pauline

**Comment by csmail** [comment]
Hi Pauline,

Apologies for the delay in my response - I was out of office due to the US
Thanksgiving break.

The file "collect_files_dt_master_tissue.txt" is generated by the scripts
outlier_var_gtex_all_outliers.r and/or outlier_var_gtex_top_outlier.r
(depending on whether you are implementing the "all outliers" or "top
outliers" methods, as discussed in the pre-print). The last line of each of
those scripts generated the file in question. It seems I named the file
slightly differently in each of these scripts - I apologize, and will amend
this in the repo now.

Craig

**Comment by pauline-ng** [comment]
Thanks!
